 CONFIG_FREERTOS_UNICORE - setup only one core

 GENERALY 2 CORES WITCH ACCESS ALL MEMORY INDEPENDETLY

2 INTERUPT PERIPHERAL

task state -> Running, Ready, Blocked, or Suspended.
portTICK_PERIOD_MS

#include "freertos/task.h"
xTaskCreatePinToCore()   //Use this two
xTaskCreateStaticPinToCore()
xTaskCreate()
xTaskCreateStatic()
vTaskDelete()
xTaskGetStaticBuffers()
vTaskDelay()
vTaskDelayUntil()
xTaskDelayUntil()
uxTaskPriorityGet()
uxTaskPriorityGetFromISR()
uxTaskBasePriorityGet()
uxTaskBasePriorityGetFromISR()
vTaskPrioritySet()
vTaskSuspend()
vTaskResume()
xTaskResumeFromISR()
xTaskAbortDelay()
uxTaskGetSystemState()
vTaskGetInfo()
xTaskGetCurrentTaskHandle()
xTaskGetIdleTaskHandle()
uxTaskGetStackHighWaterMark()
eTaskGetState()
pcTaskGetName()
xTaskGetHandle()
xTaskGetTickCount()
xTaskGetTickCountFromISR()
xTaskGetSchedulerState()
uxTaskGetNumberOfTasks()
vTaskList()
vTaskListTasks()
vTaskStartTrace()
ulTaskEndTrace()
vTaskGetRunTimeStats()
vTaskGetRunTimeStatistics()
vTaskGetIdleRunTimeCounter()
ulTaskGetRunTimeCounter()
ulTaskGetRunTimePercent()
ulTaskGetIdleRunTimeCounter()
ulTaskGetIdleRunTimePercent()
vTaskSetApplicationTaskTag()
xTaskGetApplicationTaskTag()
xTaskCallApplicationTaskHook()
pvTaskGetThreadLocalStoragePointer()
vTaskSetThreadLocalStoragePointer()
vTaskSetTimeOutState()
xTaskCheckForTimeOut()

#include "freertos/timer.h"
xTimerCreate()
xTimerCreateStatic()
xTimerIsTimerActive()
pvTimerGetTimerID()
pcTimerGetName()
vTimerSetReloadMode()
xTimerStart()
xTimerStop()
xTimerChangePeriod()
xTimerDelete()
xTimerReset()
xTimerStartFromISR()
xTimerStopFromISR()
xTimerChangePeriodFromISR()
xTimerResetFromISR()
pvTimerGetTimerID()
vTimerSetTimerID()
xTimerGetTimerDaemonTaskHandle()
xTimerPendFunctionCall()
xTimerPendFunctionCallFromISR()
pcTimerGetName()
xTimerGetPeriod()
xTimerGetExpiryTime()
xTimerGetReloadMode()



#include "freertos/queue.h"
xQueueCreate()
xQueueCreateStatic()
vQueueDelete()
xQueueSend()
xQueueSendFromISR()
xQueueSendToBack()
xQueueSendToBackFromISR()
xQueueSendToFront()
xQueueSendToFrontFromISR()
xQueueReceive()
xQueueReceiveFromISR()
uxQueueMessagesWaiting()
uxQueueMessagesWaitingFromISR()
uxQueueSpacesAvailable()
xQueueReset()
xQueuePeek()
xQueuePeekFromISR()
vQueueAddToRegistry()
pcQueueGetName()
vQueueUnregisterQueue()
xQueueIsQueueEmptyFromISR()
xQueueIsQueueFullFromISR()
xQueueOverwrite()
xQueueOverwriteFromISR()
xQueueGetStaticBuffers()



#include "freertos/semphr.h"
xSemaphoreCreateBinary()
xSemaphoreCreateBinaryStatic()
vSemaphoreCreateBinary [use xSemaphoreCreateBinary() for new designs]
xSemaphoreCreateCounting()
xSemaphoreCreateCountingStatic()
xSemaphoreCreateMutex()
xSemaphoreCreateMutexStatic()
xSemaphoreCreateRecursiveMutex()
xSemaphoreCreateRecursiveMutexStatic()
vSemaphoreDelete()
xSemaphoreGetMutexHolder()
xSemaphoreTake()
xSemaphoreTakeFromISR()
xSemaphoreTakeRecursive()
xSemaphoreGive()
xSemaphoreGiveRecursive()
xSemaphoreGiveFromISR()
uxSemaphoreGetCount()
xSemaphoreGetStaticBuffer()

